import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import axios from "axios";

const BillPreview = () => {
  const { id } = useParams();
  const [bill, setBill] = useState(null);

  useEffect(() => {
    const fetchBill = async () => {
      try {
        const token = localStorage.getItem("token");
        const { data } = await axios.get(
          `http://localhost:5003/api/bills/${id}`,
          {
            headers: {
              Authorization: `Bearer ${token}`,
            },
          }
        );
        setBill(data);
      } catch (err) {
        console.error("Failed to fetch bill:", err);
      }
    };

    fetchBill();
  }, [id]);

  if (!bill) return <p>Loading bill...</p>;

  return (
    <div className="bill-preview">
      <h2>Invoice: {bill.invoiceNumber}</h2>
      <p><strong>Customer:</strong> {bill.customerName}</p>
      <p><strong>Date:</strong> {new Date(bill.date).toLocaleString()}</p>
      <p><strong>Generated By:</strong> {bill.generatedBy}</p>
      <h3>Items:</h3>
      <ul>
        {bill.products.map((item, index) => (
          <li key={index}>
            {item.name} × {item.quantity} = ₹{item.price * item.quantity}
          </li>
        ))}
      </ul>
      <h3>Total: ₹{bill.totalAmount}</h3>
    </div>
  );
};

export default BillPreview;
